services:
  postgresql:
    image: postgres:18.3-alpine3.23
    environment:
      POSTGRES_USER: simplewallet
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: simplewallet
      RABBITMQ_DEFAULT_PASS: 123
    ports:
      - '15672:15672'
      - '5672:5672'

volumes:
  postgres_data: