services:
  simplewallet:
    build: .
    depends_on:
      - postgresql
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/simplewallet
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_RABBITMQ_PASSWORD: 123
      SECRET: arandomjwttokenshouldbeputhere
    ports:
      - '8080:8080'

  postgresql:
    image: postgres:18.3-alpine3.23
    environment:
      POSTGRES_USER: simplewallet
      POSTGRES_PASSWORD: 123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:4.3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: simplewallet
      RABBITMQ_DEFAULT_PASS: 123
    ports:
      - '15672:15672'
      - '5672:5672'

volumes:
  postgres_data: