spring.application.name=SimpleWallet

spring.datasource.url=jdbc:postgresql://localhost:5432/simplewallet
spring.datasource.username=simplewallet
spring.datasource.password=123

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=simplewallet
spring.rabbitmq.password=123